language: node_js

node_js:
  - 8

cache:
  directories:
    - node_modules

script:
  - npm run lint
  - npm run test-deps
  - npm run cover

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - npm run build

before_deploy:
  - tar --transform "s|build/stencila-cli-linux|stencila|" -czvf build/stencila-linux-x64.tar.gz build/stencila-cli-linux
  - tar --transform "s|build/stencila-cli-macos|stencila|" -czvf build/stencila-macos-x64.tar.gz build/stencila-cli-macos
  - mv build/stencila-cli-win.exe build/stencila.exe ; zip -j build/stencila-win-x64.zip build/stencila.exe

deploy:
  on:
    tags: true
  provider: releases
  api_key:
    secure: "lhwXNRW1oJfUINxcDmJ0vp6sIiuB4BGaLiAaBArAiovCfPrqb+c+T+gALpLSxpWCl6gGm99wNjaOLS0SGI4xg88833ZScm0Y+qDaGUgxGSvy//GVFmqxoMImyg4MKEKaTAkOLr60OEdfSor0pLkxPCmf0NRG8LATKLsyIJ6eG0kr7tRW7KdeegCeWZNpGvycLmql4WSRS/f+229CXrsALwxn46eGbNoGTHiAP+dKrTalqFEgpkvxDpPmUy9ou4m8CMIEZhZbu7T/zr2zqo0vhPoeL1a/3lAxyRJJHYwxUkAED6QPRxy+VDG14YrMtGV1yuPxInbt910jPofp2Gi2R12/tYrBTSHOjcDd+qZ0sm7rDR4lHVnXWEL9okQlnmRVD++sQb7OwRvBQpztsi8BrDICLIoLwO54kofinht6ClABZg9CcTVSUj/61VvO+Ud+eFO+9VX623TFwXGG2tQ8U5q6gn71siLf6BPAJdatM9kHXQ6ecB8KIZvPK5+gDv/sDWpHGkL1E6AsSNFvWiH4ACuqOD6gYw2sNd1wmfTH2cJ3AywBnJUdBukVXXpan19lGUv6vF5zZ50l9Tq1fU5v8wzNh5CUeWBXNujAYEU5nzhkMiBJIIt+K/SrIg3KEi7+UnhsJjA9Y7kwYJfmEFQbMQgEpqPhl9T+oFTb4fNKm9g="
  file:
    - build/stencila-linux-x64.tar.gz
    - build/stencila-macos-x64.tar.gz
    - build/stencila-win-x64.zip
  skip_cleanup: true
